name: infinite_timesweeper
description: "Simple, configurable and beautiful implementation of minesweeper with infinite world."
publish_to: 'none'
version: 0.0.4+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.32.0
  shared_preferences: ^2.3.3
  path_provider: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_icons:
   android: true
   ios: false
   image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/audio/
